services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - json-server

    json-server:
        build:
            context: .
            dockerfile: Dockerfile_server
        ports:
            - '3001:3001'
